LANG_UI = {
    "uk": {
        "welcome": "📚 <b>Ласкаво просимо до CyberLibrary PRO</b>\n\nПереглядайте категорії, генеруйте випадкову підбірку або спілкуйтеся з глобальним ШІ:",
        "feed_title": "📚 <b>Категорія: {genre}</b> (Усього: {count})",
        "feed_empty": "❌ У цій категорії поки що немає книг.",
        "rand_title": "🎲 <b>Ось 5 випадкових книг з бази:</b>",
        "book_card": "📖 <b>{title}</b>\n✍️ <b>Автор:</b> {author}\n\n📝 <b>Опис:</b>\n{desc}",
        "chat_init": "💬 <b>Канал Обговорення Відкрито!</b>\nКнига: <b>{title}</b>, автор {author}.\n\nЯкі елементи сюжету, розвиток персонажів чи приховані сенси ви хочете розібрати?",
        "fav_title": "⭐ <b>Ваші Закладки:</b>",
        "fav_empty": "⭐ У вас ще немає закладок. Додайте книги з каталогу!",
        "fav_added": "✅ Книгу додано до закладок!",
        "fav_removed": "❌ Книгу видалено з закладок.",
        "search_local_title": "🔍 <b>Результати пошуку:</b> <code>{query}</code>",
        "search_local_prompt": "🔍 Введіть назву книги або автора для пошуку в базі:",
        "search_prompt": "🔍 Введіть назву книги для глобального пошуку ШІ:",
        "search_global_title": "🌐 <b>Результати глобального пошуку:</b>",
        "search_empty": "😕 На жаль, нічого не знайдено.",
        "chat_global_init": "🌟 <b>{book}</b>\n\n💬 Критична сесія активна! Надішліть будь-яке повідомлення для аналізу тем, мотивів або сюжетних ліній.",
        "err_api": "⚠️ Помилка з'єднання з AI. Спробуйте пізніше.",
        "err_empty": "❌ Книгу не знайдено.",
        "err_empty_ai": "🤖 AI не знайшов відповідей за вашим запитом.",
        "err_parse_ai": "⚠️ AI повернув некоректні дані. Спробуйте ще раз.",
        "ai_sys_search": "Проаналізуй запит користувача: '{query}'. Знайди до 3 реальних книг, які найкраще відповідають. Для кожної книги надай: Назва | Автор | Короткий опис (2 речення). Якщо не можеш ідентифікувати конкретні книги, поверни рядок 'NOT_FOUND'. Відповідай СТРОГО у форматі JSON-масиву рядків. Приклад: [\"Назва1 | Автор1 | Опис1\", \"Назва2 | Автор2 | Опис2\"]",
        "ai_sys_critics_role": "Ти — літературний критик і філософ. Твоя задача — давати глибокий, критичний, але конструктивний аналіз книг.",
        "ai_sys_critics": "Ти ведеш діалог з читачем про книгу '{title}' автора {author}.\n\nОсь опис книги:\n{description}\n\nІсторія діалогу:\n{history}\n\nКористувач щойно написав: '{query}'.\n\nДай розгорнуту, критичну відповідь. Проаналізуй запит користувача в контексті цієї книги. Якщо це загальне питання, дай філософську оцінку.",
        "ai_sys_global_critics": "Ти — літературний критик. Користувач обрав книгу: '{book}'.\n\nІсторія діалогу:\n{history}\n\nКористувач пише: '{query}'.\n\nДай глибокий критичний аналіз. Якщо книга невідома, скажи про це чесно.",
        "btn_scifi": "Наукова фантастика",
        "btn_fantasy": "Фентезі",
        "btn_romance": "Романтика",
        "btn_mystery": "Детектив",
        "btn_hist": "Історичний",
        "btn_ya": "YA",
        "btn_horror": "Жахи",
        "btn_nonfiction": "Нон-фікшн",
        "btn_random": "🎲 Випадкова підбірка",
        "btn_global_ai": "🌐 Глобальний пошук ШІ",
        "search_prompt": "🔍 Введіть назву книги або опис для глобального пошуку ШІ:",
        "btn_refresh": "🔄 Ще 5",
        "btn_search": "🔍 Пошук",
        "btn_favorites": "⭐ Закладки",
        "btn_change_lang": "🌐 Мова",
        "btn_discuss_ai": "💬 AI Критик",
        "btn_add_fav": "⭐ Додати",
        "btn_remove_fav": "❌ Видалити",
        "btn_gr": "📖 Goodreads",
        "btn_back": "🔙 Назад",
        "btn_exit_chat": "🔙 Вийти з чату",
    },
    "en": {
        "welcome": "📚 <b>Welcome to CyberLibrary PRO Main Portal</b>\n\nBrowse native categories, run a randomized mix, or chat with the global AI engine:",
        "feed_title": "📚 <b>Genre Feed: {genre}</b> (Total Loaded: {count})",
        "feed_empty": "❌ No books found in this category yet.",
        "rand_title": "🎲 <b>Here are 5 random selections from your index:</b>",
        "book_card": "📖 <b>{title}</b>\n✍️ <b>Author:</b> {author}\n\n📝 <b>Summary:</b>\n{desc}",
        "chat_init": "💬 <b>Active Discussion Channel Configured!</b>\nTarget Volume: <b>{title}</b> by {author}.\n\nWhat elements, character arcs, or plot structures do you want to dissect?",
        "fav_title": "⭐ <b>Your Bookmarks:</b>",
        "fav_empty": "⭐ You have no bookmarks yet. Add books from the catalog!",
        "fav_added": "✅ Book added to bookmarks!",
        "fav_removed": "❌ Book removed from bookmarks.",
        "search_local_title": "🔍 <b>Search results for:</b> <code>{query}</code>",
        "search_local_prompt": "🔍 Enter a book title or author to search the database:",
        "search_prompt": "🔍 Enter a book title for global AI search:",
        "search_global_title": "🌐 <b>Global AI Search Results:</b>",
        "search_empty": "😕 Unfortunately, nothing was found.",
        "chat_global_init": "🌟 <b>{book}</b>\n\n💬 Critical session active! Send any query to analyze themes, motifs, or character arcs.",
        "err_api": "⚠️ AI connection error. Please try again later.",
        "search_prompt": "🔍 Enter a book title or description for global AI search:",
        "btn_refresh": "🔄 New 5",
        "err_empty": "❌ Book not found.",
        "err_empty_ai": "🤖 AI found no matches for your query.",
        "err_parse_ai": "⚠️ AI returned invalid data. Please try again.",
        "ai_sys_search": "Analyze the search request: '{query}'. Find up to 3 real books that best match. For each book provide: Title | Author | Short description (2 sentences). If you cannot identify specific books, return the string 'NOT_FOUND'. Respond STRICTLY in a JSON array of strings. Example: [\"Title1 | Author1 | Desc1\", \"Title2 | Author2 | Desc2\"]",
        "ai_sys_critics_role": "You are a literary critic and philosopher. Your task is to provide deep, critical, yet constructive analysis of books.",
        "ai_sys_critics": "You are having a dialogue with a reader about the book '{title}' by {author}.\n\nHere is the book description:\n{description}\n\nDialogue history:\n{history}\n\nThe user just wrote: '{query}'.\n\nGive a detailed, critical response. Analyze the user's query in the context of this book. If it is a general question, give a philosophical evaluation.",
        "ai_sys_global_critics": "You are a literary critic. The user selected the book: '{book}'.\n\nDialogue history:\n{history}\n\nUser writes: '{query}'.\n\nProvide a deep critical analysis. If the book is unknown, be honest about it.",
        "btn_scifi": "Sci-Fi",
        "btn_fantasy": "Fantasy",
        "btn_romance": "Romance",
        "btn_mystery": "Mystery",
        "btn_hist": "Historical",
        "btn_ya": "YA",
        "btn_horror": "Horror",
        "btn_nonfiction": "Non-Fiction",
        "btn_random": "🎲 Random Mix",
        "btn_global_ai": "🌐 Global AI",
        "btn_search": "🔍 Search",
        "btn_favorites": "⭐ Bookmarks",
        "btn_change_lang": "🌐 Language",
        "btn_discuss_ai": "💬 AI Critics",
        "btn_add_fav": "⭐ Add",
        "btn_remove_fav": "❌ Remove",
        "btn_gr": "📖 Goodreads",
        "btn_back": "🔙 Back",
        "btn_exit_chat": "🔙 Exit Chat",
    },
}